### ISSUE TITLE
BUG from source

### ISSUE THREAD

**Issue by ne-vlezay80** [pborman/uuid#49]
go get -t -v -d ./...
CC=cc go install -v -tags "libsqlite3"  ./...
github.com/pborman/uuid
github.com/CanonicalLtd/go-dqlite/internal/bindings
github.com/CanonicalLtd/go-dqlite/internal/trace
github.com/armon/go-metrics
# github.com/pborman/uuid
../../pborman/uuid/time.go:15: syntax error: unexpected = in type declaration
github.com/miekg/dns
# github.com/CanonicalLtd/go-dqlite/internal/trace
../../CanonicalLtd/go-dqlite/internal/trace/set.go:112: undefined: sort.Slice
# github.com/armon/go-metrics
../../armon/go-metrics/inmem_endpoint.go:72: undefined: sort.Slice
../../armon/go-metrics/inmem_endpoint.go:86: undefined: sort.Slice
../../armon/go-metrics/inmem_endpoint.go:113: undefined: sort.Slice
# github.com/miekg/dns
../../miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
../../miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
# github.com/CanonicalLtd/go-dqlite/internal/bindings
../../CanonicalLtd/go-dqlite/internal/bindings/testing.go:13: t.Helper undefined (type *testing.T has no field or method Helper)
../../CanonicalLtd/go-dqlite/internal/bindings/server.go:26: constant -8786437285571510299 overflows uint64
Makefile:18: ошибка выполнения рецепта для цели «default»
make: *** [default] Ошибка 2

**Comment by pborman** [comment]
I cannot reproduce this error.  The uuid package builds and tests cleanly.

**Comment by sbinet** [comment]
I suspect this error comes from using a very old Go version where `sort.Slice` wasn't defined yet, and where type-alias wasn't in either.

**Comment by declan** [comment]
I got this error on a machine with Go 1.6 installed. It went away when I upgraded to 1.9.2.

**Comment by pborman** [comment]
Closing this as it is due to an old version of Go.
